name: Python package

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ['3.7', '3.8', '3.9', '3.10', '3.11']

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install poetry
        poetry install -E toml -E yaml

    - name: Lint with flake8
      if: ${{ matrix.python-version == '3.10' }}
      run: poetry run flake8

    - name: Check formatting with black
      if: ${{ matrix.python-version == '3.10' }}
      run: poetry run black --check .

    - name: Sort imports
      if: ${{ matrix.python-version == '3.10' }}
      run: poetry run isort -c --df .

    - name: Test with pytest
      run: poetry run pytest --cov=coleo --cov-report term-missing

    - name: Verify coverage
      run: poetry run coverage report | tail -1 | egrep "TOTAL +[0-9]+ +0 +100%"
